StokTakip(Deneme)/Controllers/UrunlerController.cs
using StokTakip_Deneme_.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using System.Security.Cryptography.Xml;
using System.Security.Cryptography;
using System.Data.Entity;

namespace StokTakip_Deneme_.Controllers
{

    [Authorize]
    public class UrunlerController : Controller
    {
  Stock_Tracking_AppEntities2 db = new Stock_Tracking_AppEntities2();

        public ActionResult Index()
        {
            var model = db.Urunler.ToList();  
            return View(model);

        }
        [HttpGet]
        public ActionResult Ekle ()
        {
            var model = new Urunler();

            Yenile(model);

            return View(model);
        }

        private void Yenile(Urunler model)
        {
            List<Kategoriler> KategoriList = db.Kategoriler.OrderBy(x => x.Kategori).ToList();

            model.KategoriListesi = (from x in KategoriList
                                     select new SelectListItem
                                     {

                                         Text = x.Kategori,
                                         Value = x.ID.ToString()


                                     }).ToList();


            List<Birimler> BirimList = db.Birimler.OrderBy(x => x.Birim).ToList();


            model.BirimListesi = (from x in BirimList
                                  select new SelectListItem
                                  {

                                      Text = x.Birim,
                                      Value = x.ID.ToString()


                                  }).ToList();
        }



        [HttpPost]


        public ActionResult Ekle ( Urunler p )
        
        {
            if (!ModelState.IsValid)
            {
                var model = new Urunler();

                Yenile(model);

                return View(model);
            }
            db.Entry(p).State = System.Data.Entity.EntityState.Added;
            db.SaveChanges  (); 
            return RedirectToAction("Index");
        
        
        }


        public JsonResult GetMarka  (int id2 )
        {
            var model = new Urunler();


            List<Markalar> MarkaList = db.Markalar.Where(x=>x.KategoriID==id2).OrderBy(x => x.Marka).ToList();


            model.MarkaListesi = (from x in MarkaList
                                  select new SelectListItem
                                  {

                                      Text = x.Marka,
                                      Value = x.ID.ToString()


                                  }).ToList();
 
            return Json(model.MarkaListesi, JsonRequestBehavior.AllowGet);
       
        }


        [HttpGet]
        public ActionResult GuncelleBilgiGetir(int id)
        {


            var model = db.Urunler.Find(id); 
            Yenile(model);
            List<Markalar> MarkaList = db.Markalar.Where(x => x.KategoriID ==model.KategoriID).OrderBy(x => x.Marka).ToList();


            model.MarkaListesi = (from x in MarkaList
                                  select new SelectListItem
                                  {

                                      Text = x.Marka,
                                      Value = x.ID.ToString()


                                  }).ToList();

            return View(model);


        }
        [HttpPost]

        public ActionResult Guncelle(Urunler p)
        {
            if (!ModelState.IsValid)
            {
                var model = db.Urunler.Find(p.ID);
                Yenile(model);
                List<Markalar> markaList = db.Markalar
                    .Where(x => x.KategoriID == model.KategoriID)
                    .OrderBy(x => x.Marka)
                    .ToList();

                model.MarkaListesi = markaList
                    .Select(x => new SelectListItem
                    {
                        Text = x.Marka,
                        Value = x.ID.ToString()
                    })
                    .ToList();

                return View("GuncelleBilgiGetir", model); // Hata durumunda aynı view'ı tekrar göster
            }

            db.Entry(p).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult SilBilgiGetir(Urunler p)
        {

            var model = db.Urunler.Find(p.ID);
            return View(model);
        }
        public ActionResult Sil (Urunler p )

        {

          
            db.Entry(p).State=System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");  
        }
    }
}

StokTakip(Deneme)/Views/Urunler/Ekle.cshtml
@model StokTakip_Deneme_.Models.Entity.Urunler

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ürün Ekleme Sayfası</h2>

<div class="container">
    @using (Html.BeginForm("Ekle", "Urunler", FormMethod.Post))
    {
        <div class="form-group">
            @Html.LabelFor(x => x.KategoriID, "Kategori")
            @Html.DropDownListFor(x => x.KategoriID, Model.KategoriListesi, "---- Seçiniz ----", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.KategoriID, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MarkaID, "Marka")
            @Html.DropDownListFor(x => x.MarkaID, Model.MarkaListesi, "---- Seçiniz ----", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MarkaID, "", new { @class = "text-danger" })
        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.UrunAdi, "Ürün Adı")
            @Html.TextBoxFor(x => x.UrunAdi, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.UrunAdi, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.BarkodNo, "Barkod No")
            @Html.TextBoxFor(x => x.BarkodNo, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.BarkodNo, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.AlisFiyati, "Alış Fiyatı")
            @Html.TextBoxFor(x => x.AlisFiyati, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AlisFiyati, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.SatisFiyati, "Satış Fiyatı ")
            @Html.TextBoxFor(x => x.SatisFiyati, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.SatisFiyati, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Miktari, "Miktarı")
            @Html.TextBoxFor(x => x.Miktari, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Miktari, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.KDV, "KDV")
            @Html.TextBoxFor(x => x.KDV, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.KDV, "", new { @class = "text-danger" })

        </div>


        <div class="form-group">
            @Html.LabelFor(x => x.Birimler.Birim, "Birim")
            @Html.DropDownListFor(x => x.BirimID, Model.BirimListesi, "---- Seçiniz ----", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.BirimID, "", new { @class = "text-danger" })
        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Tarih, "Tarih")
            @Html.TextBoxFor(x => x.Tarih, new { type = "date" })
            @Html.ValidationMessageFor(x => x.Tarih, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Aciklama, "Aciklama")
            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Aciklama, "", new { @class = "text-danger" })

        </div>
        if (User.IsInRole("ceo")|| User.IsInRole("personel"))
        {
            <div>
                <button class="btn btn-success"> Ürün Ekle </button>
            </div>
            }
        }
    </div>

@section scripts
{
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#KategoriID").change(function () {
                var ID = $(this).val();
                var markalist = $("#MarkaID");
                markalist.empty();
                $.ajax({
                    url: '/Urunler/GetMarka/',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'id2': ID },
                    success: function (data) {
                        $.each(data, function (index, option) {
                            markalist.append('<option value=' + option.Value + '>' + option.Text + '</option>');
                        });
                    }
                });
            });
        });
    </script>
}

StokTakip(Deneme)/Views/Urunler/GuncelleBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Urunler
@{
    ViewBag.Title = "GuncelleBilgiGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ürün Güncelleme Sayfası </h2>

<div class="container">
    @using (Html.BeginForm("Guncelle", "Urunler", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x=>x.ID)

        <div class="form-group">
            @Html.LabelFor(x => x.KategoriID, "Kategori")
            @Html.DropDownListFor(x => x.KategoriID, Model.KategoriListesi, "---- Seçiniz ----", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.KategoriID, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MarkaID, "Marka")
            @Html.DropDownListFor(x => x.MarkaID, Model.MarkaListesi, "---- Seçiniz ----", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.MarkaID, "", new { @class = "text-danger" })
        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.UrunAdi, "Ürün Adı")
            @Html.TextBoxFor(x => x.UrunAdi, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.UrunAdi, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.BarkodNo, "Barkod No")
            @Html.TextBoxFor(x => x.BarkodNo, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.BarkodNo, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.AlisFiyati, "Alış Fiyatı")
            @Html.TextBoxFor(x => x.AlisFiyati, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.AlisFiyati, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.SatisFiyati, "Satış Fiyatı ")
            @Html.TextBoxFor(x => x.SatisFiyati, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.SatisFiyati, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Miktari, "Miktarı")
            @Html.TextBoxFor(x => x.Miktari, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Miktari, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.KDV, "KDV")
            @Html.TextBoxFor(x => x.KDV, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.KDV, "", new { @class = "text-danger" })

        </div>


        <div class="form-group">
            @Html.LabelFor(x => x.Birimler.Birim, "Birim")
            @Html.DropDownListFor(x => x.BirimID, Model.BirimListesi, "---- Seçiniz ----", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.BirimID, "", new { @class = "text-danger" })
        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Tarih, "Tarih")
            @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control", type = "date" })
            @Html.ValidationMessageFor(x => x.Tarih, "", new { @class = "text-danger" })

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Aciklama, "Aciklama")
            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Aciklama, "", new { @class = "text-danger" })

        </div>
        <div>
            <button class="btn btn-primary"> Ürün Güncelle </button>
            <a href="/Urunler/Index/">Ana Sayfa </a>
        </div>
    }
</div>


@section scripts
{
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#KategoriID").change(function () {
                var ID = $(this).val();
                var markalist = $("#MarkaID");
                markalist.empty();
                $.ajax({
                    url: '/Urunler/GetMarka/',
                    type: 'POST',
                    dataType: 'json',
                    data: { 'id2': ID },
                    success: function (data) {
                        $.each(data, function (index, option) {
                            markalist.append('<option value=' + option.Value + '>' + option.Text + '</option>');
                        });
                    }
                });
            });
        });
    </script>
}

StokTakip(Deneme)/Views/Urunler/Index.cshtml
@model List<StokTakip_Deneme_.Models.Entity.Urunler>

@using StokTakip_Deneme_.Models.Entity

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!DOCTYPE html>
<html>
<head>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f0f0f0;
        }

        .div {
            background-color: #e0e0e0;
            padding: 10px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>

    <div class="container">
        <h2>Ürün Listeleme </h2>
        @foreach (var item in Model)
        {
            <div class="div">
                <tr>
                    <p><b>ID: </b>@item.ID</p>
                    <P><b>KATEGORİ: </b>@item.Kategoriler.Kategori</P>
                    <p><b>MARKA: </b>@item.Markalar.Marka</p>
                    <p><b>ÜRÜN ADI: </b>@item.UrunAdi</p>
                </tr>
                <div id="details-@item.ID" style="display: none;">

                    <p><b>BARKOD NO: </b>@item.BarkodNo</p>
                    <p><b>ALIŞ FİYATI: </b>@item.AlisFiyati</p>
                    <p><b>SATIŞ FİYATI: </b>@item.SatisFiyati</p>
                    <p><b>MİKTARI: </b>@item.Miktari</p>
                    <p><b>KDV: </b>% @item.KDV</p>
                    <p><b>BİRİM: </b>@item.Birimler.Birim</p>
                    <p><b>TARİH: </b>@item.Tarih</p>
                    <p><b>AÇIKLAMA: </b>@item.Aciklama</p>
                </div>
                @if (User.IsInRole("ceo") || User.IsInRole("personel"))
                {
                    <th><a href="/Urunler/SilBilgiGetir/@item.ID" class="btn btn-danger">Sil</a></th>
                    <th><a href="/Urunler/GuncelleBilgiGetir/@item.ID" class="btn btn-warning">Güncelle</a></th>
                }

                <button class="btn btn-info" onclick="showDetails(@item.ID)">Daha Fazla</button>
            </div>
        }
        @if (User.IsInRole("ceo") || User.IsInRole("personel"))
        {
            <div style="width: 250px ">
                <a href="/Urunler/Ekle/" class="btn btn-success" style="margin-top:10px;">
                    Ürün Ekle
                </a>
            </div>
        }
    </div>

</body>
</html>

<script>
    function showDetails(itemId) {
        var detailsDiv = document.getElementById("details-" + itemId);
        if (detailsDiv.style.display === "none") {
            detailsDiv.style.display = "block";
        } else {
            detailsDiv.style.display = "none";
        }
    }
</script>

StokTakip(Deneme)/Views/Urunler/SilBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Urunler
@{
    ViewBag.Title = "Sil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Ürün Silme </h2>

<div class="container">
    @using (Html.BeginForm("Sil", "Urunler", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.ID)

        <div class="form-group">
            @Html.LabelFor(x => x.KategoriID, "Kategori")
            @Html.TextBoxFor(x => x.KategoriID, Model.KategoriListesi)

        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.MarkaID, "Marka")
            @Html.TextBoxFor(x => x.MarkaID, Model.MarkaListesi)

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.UrunAdi, "Ürün Adı")
            @Html.TextBoxFor(x => x.UrunAdi, new { @class = "form-control" })


        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.BarkodNo, "Barkod No")
            @Html.TextBoxFor(x => x.BarkodNo, new { @class = "form-control" })


        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.AlisFiyati, "Alış Fiyatı")
            @Html.TextBoxFor(x => x.AlisFiyati, new { @class = "form-control" })


        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.SatisFiyati, "Satış Fiyatı ")
            @Html.TextBoxFor(x => x.SatisFiyati, new { @class = "form-control" })


        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Miktari, "Miktarı")
            @Html.TextBoxFor(x => x.Miktari, new { @class = "form-control" })


        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.KDV, "KDV")
            @Html.TextBoxFor(x => x.KDV, new { @class = "form-control" })


        </div>


        <div class="form-group">
            @Html.LabelFor(x => x.Birimler.Birim, "Birim")
            @Html.TextBoxFor(x => x.BirimID, Model.BirimListesi)

        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Tarih, "Tarih")
            @Html.TextBoxFor(x => x.Tarih, new { type = "date" })


        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Aciklama, "Aciklama")
            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })


        </div>
        if (User.IsInRole("ceo") || User.IsInRole("personel"))
        {
             <div>
           <button class="btn btn-danger"> Ürünü Sil </button>
          <a href="/Urunler/Index/">Ana Sayfa </a>
           </div> 
        }
    }
    
    
</div>