StokTakip(Deneme)/Controllers/MarkalarController.cs
using StokTakip_Deneme_.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StokTakip_Deneme_.Controllers
{

    [Authorize(Roles = "ceo")]
    public class MarkalarController : Controller
    {
        Stock_Tracking_AppEntities2 db = new Stock_Tracking_AppEntities2();
        public ActionResult Index()
        {

            var model = db.Markalar.ToList();
            return View(model);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            SelecteBilgiGetir();
            return View();

        }

        private void SelecteBilgiGetir()
        {
            var model = new Markalar();

            List<SelectListItem> Liste = new List<SelectListItem>(from x in db.Kategoriler

                                                                  select new SelectListItem
                                                                  {
                                                                      Value = x.ID.ToString(),
                                                                      Text = x.Kategori

                                                                  }

                                                                    ).ToList();

            ViewBag.l = Liste;
        }

        [HttpPost]
        public ActionResult Ekle(Markalar p)

        {
            if (!ModelState.IsValid)
            {
                ViewBag.KategoriID = new SelectList(db.Kategoriler, "ID", "Kategori", p.KategoriID);
                return View();
            }
            
            db.Markalar.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult GuncelleBilgiGetir (int id ) 
        
        {
            SelecteBilgiGetir(); 
            var ara = db.Markalar.Find(id); 
            return View(ara);        
        }

        public ActionResult Guncelle ( Markalar p)
        {
            if (!ModelState.IsValid)
            {
                SelecteBilgiGetir();
                return View("GuncelleBilgiGetir");
            }

            db.Entry(p).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SilBilgiGetir(Markalar p )
            
        {

            var getir = db.Markalar.Find(p.ID); 

            return View(getir);
        
        }
        public ActionResult Sil (Markalar p  )
        { 

             db.Entry(p).State= System.Data.Entity.EntityState.Deleted; db.SaveChanges();
            return RedirectToAction("Index");   
        }
    }
}

StokTakip(Deneme)/Views/Markalar/Ekle.cshtml
@model StokTakip_Deneme_.Models.Entity.Markalar

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Marka Ekleme</h2>

<div class="container">

    @using (Html.BeginForm("Ekle", "Markalar", FormMethod.Post))

    {

        <div class=" form-group">
            @Html.LabelFor(x => x.Kategoriler.Kategori)
            @Html.DropDownListFor(x=>x.KategoriID,  (List<SelectListItem>)ViewBag.l , "---- Seçiniz ---- ", new { @class = "form-control " })
            @Html.ValidationMessageFor(x => x.Kategoriler, "", new { @class = " text-danger" })
        </div>
     
        <div class=" form-group">
            @Html.LabelFor(x => x.Marka)
            @Html.TextBoxFor(x => x.Marka, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Marka, "", new { @class = " text-danger" })
        </div>

        <div class=" form-group">
            @Html.LabelFor(x => x.Aciklama)
            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Aciklama, "", new { @class = " text-danger" })
        </div>

        <div>
            <button class="btn btn-success"> Marka Ekle </button>
        </div>
    }

</div>

StokTakip(Deneme)/Views/Markalar/GuncelleBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Markalar 
@{
    ViewBag.Title = "GuncelleBilgiGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Marka Güncelleme Sayfası </h2>

<div class="container ">

    @using (Html.BeginForm("Guncelle", "Markalar"))

    {

        @Html.HiddenFor(x => x.ID)
        <div class=" form-group">
            @Html.LabelFor(x => x.Kategoriler.Kategori)
            @Html.DropDownListFor(x => x.KategoriID, (List<SelectListItem>)ViewBag.l, "---- Seçiniz ---- ", new { @class = "form-control" })
            @Html.ValidationMessageFor(x=>x.KategoriID, null , new {@class = "text-danger"})
        </div>

        <div class=" form-group">
            @Html.LabelFor(x => x.Marka)
            @Html.TextBoxFor(x => x.Marka, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Marka, null, new { @class = "text-danger" })
        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Aciklama)
            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Aciklama, null, new { @class = "text-danger" })
        </div>
         <div class=" form-group  ">

             <button class=" btn btn-success">Markayı Güncelle</button>
             <a href="/Markalar/Index">Ana Sayfa</a>
         </div>
    }
</div>

StokTakip(Deneme)/Views/Markalar/Index.cshtml
@using StokTakip_Deneme_.Models.Entity
@model List<StokTakip_Deneme_.Models.Entity.Markalar>

@using StokTakip_Deneme_.Models.Entity


@{
    ViewBag.Title = "Markalar";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f0f0f0;
        }

        .div {
            background-color: #e0e0e0;
            padding: 10px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    
    <div class="container">
       
        <h2>@ViewBag.Title</h2>
        
        <body>

            @foreach (var item in Model)
            {
                <div class="div">
                    <tr>
                        <p><b>ID: </b>@item.ID</p>
                        <p><b>KATEGORİ ID: </b>@item.Kategoriler.Kategori</p>
                        <p><b>MARKA: </b>@item.Marka</p>
                        <p><b>AÇIKLAMA: </b>@item.Aciklama</p>


                    </tr>
                    <tr>
                        <td> <a href="/Markalar/SilBilgiGetir/@item.ID" class="btn btn-danger">Sil</a></td>
                        <td> <a href="/Markalar/GuncelleBilgiGetir/@item.ID" class="btn btn-warning">Güncelle</a></td>
                    </tr>
                </div>
            }
        </body>
        <div style="width: 250px ">

            <a href="/Markalar/Ekle/" class=" btn btn-success" style="margin-top:10px;">
                Marka Ekle
            </a>


        </div>
    </div>

</body>
</html>

StokTakip(Deneme)/Views/Markalar/SilBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Markalar
@{
    ViewBag.Title = "SilBilgiGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Marka Silme Sayfası </h2>




<div class=" container ">

    @using(Html.BeginForm("Sil", "Markalar") )
{
    @Html.HiddenFor(x => x.ID)

    <div class=" form-group">
        <b>@Html.LabelFor(x => x.Kategoriler.Kategori): </b>
        @Html.DisplayFor(x => x.Kategoriler.Kategori)
    </div>
    <div class=" form-group">
        <b>@Html.LabelFor(x => x.Marka): </b>
        @Html.DisplayFor(x => x.Marka)
    </div> 
    <div class=" form-group">
        <b>@Html.LabelFor(x => x.Aciklama): </b>
        @Html.DisplayFor(x => x.Aciklama)
    </div>
    <div>
        <button class=" btn btn-danger">Markayı sil </button>
        <a href="/Markalar/Index">Anasayfa</a>
    </div>
    }
</div>