StokTakip(Deneme)/Controllers/KategorilerController.cs
using StokTakip_Deneme_.Models.Entity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using static System.Web.Razor.Parser.SyntaxConstants;
using System.Web.UI.WebControls;

namespace StokTakip_Deneme_.Controllers
{

    [Authorize(Roles ="ceo")]
    public class KategorilerController : Controller
    {
        Stock_Tracking_AppEntities2 db = new Stock_Tracking_AppEntities2();

        public ActionResult Index()
        {
            return View(db.Kategoriler.ToList());

        }

        public ActionResult Ekle()
        {
            return View();
        }
        public ActionResult Ekle2(Kategoriler p)
        {
            if (!ModelState.IsValid)
            {
                return View("Ekle");
            }
            db.Kategoriler.Add(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult GuncelleBilgiGetir(Kategoriler p)

        {
            var model = db.Kategoriler.Find(p.ID);

            return View(model);
        }

        public ActionResult Guncelle(Kategoriler p)
        {
            db.Entry(p).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }



         public ActionResult SilBilgiGetir(Kategoriler p )
        {
            var model = db.Kategoriler.Find(p.ID); 

            if(model== null  ) return HttpNotFound();   

             return View(model) ;
        }

        public ActionResult Sil (Kategoriler p )
        {


            db.Entry(p).State= System.Data.Entity.EntityState.Deleted; 
            db.SaveChanges();
            return RedirectToAction("Index"); 
        }



        }


       
}

StokTakip(Deneme)/Views/Kategoriler/Ekle.cshtml
@model StokTakip_Deneme_.Models.Entity.Kategoriler

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kategori Ekleme</h2>

<div class="container">
    <form method="post" action="/Kategoriler/Ekle2">
        @Html.AntiForgeryToken()

        <div class="form-group">
            <label for="Kategori">Kategori</label>
            <input type="text" id="Kategori" name="Kategori" class="form-control" />

        </div>
        @Html.ValidationMessageFor(x => x.Kategori, "", new { @class = "text-danger" })
        <div class="form-group">
            <label for="Aciklama">Açıklama</label>
            <textarea id="Aciklama" name="Aciklama" class="form-control"></textarea>
        </div>
        @Html.ValidationMessageFor(x => x.Aciklama, "", new { @class = "text-danger" })
        <div class="form-group">
            <button type="submit" class="btn btn-success">Kategori Ekle</button>
        </div>
    </form>
</div>

StokTakip(Deneme)/Views/Kategoriler/GuncelleBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Kategoriler
@{
    ViewBag.Title = "GuncelleBilgiGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kategori Güncelleme</h2>

<div    class="container">
    <form action="/Kategoriler/Guncelle">

        <div class="form-group">
            <b>ID</b>

            @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
        </div>


        <div class="form-group">
            <b>Kategori</b>

            @Html.TextBoxFor(x => x.Kategori, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <b>Açıklama</b>

            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
        </div>

        <div  class="form-group">
             <button class="btn btn-success"> Kategori Güncelle </button>
        </div>
    </form>

</div>

StokTakip(Deneme)/Views/Kategoriler/Index.cshtml
@model List<StokTakip_Deneme_.Models.Entity.Kategoriler>
@using StokTakip_Deneme_.Models.Entity


@{
    ViewBag.Title = "Kategoriler Listesi ";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f0f0f0;
        }

        .div {
            background-color: #e0e0e0;
            padding: 10px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    
    <div class="container">
        <h2>@ViewBag.Title</h2>

        @foreach (var item in Model)
        {
         
            <div class="div">
                <tr>
                    <p>
                    <b>ID</b>
                    @item.ID</p>
                    <p>
                    <b>Kategori</b>
                    @item.Kategori</p>
                    <p>
                    <b>Açıklama</b>
                    @item.Aciklama</p>
                    <th><a href="/Kategoriler/SilBilgiGetir/@item.ID" class="btn btn-danger">Sil</a></th>
                    <th><a href="/Kategoriler/GuncelleBilgiGetir/@item.ID" class="btn btn-warning">Güncelle</a></th>
                </tr>
            </div>
        }
        @if (User.IsInRole("ceo") || User.IsInRole("personel"))
        {

            <div style="width: 250px;">
                <a href="/Kategoriler/Ekle" class="btn btn-success" style="margin-top: 10px;">Kategori Ekle</a>
            </div>
        }
    </div>

</body>
</html>

StokTakip(Deneme)/Views/Kategoriler/SilBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Kategoriler



@{
    ViewBag.Title = "SilBilgiGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> Kategori Silme Sayfası </h2>



<div class=" container ">



    @using (Html.BeginForm("Sil", "Kategoriler"))

    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.ID)
        <div class=" form-group">

            @Html.LabelFor(x => x.Kategori)
            @Html.DisplayFor(x => x.Kategori, new { @class = "form-control " })
        </div>
        <div class=" form-group">
            @Html.LabelFor(x => x.Aciklama)
            @Html.DisplayFor(x => x.Aciklama, new { @class = "form-control " })
        </div>
        <div>
            <button class=" btn btn-danger">Kategori sil </button>
            <a href="/Kategoriler/Index">Anasayfa</a>
        </div>

    }

</div>