StokTakip(Deneme)/Controllers/BirimlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StokTakip_Deneme_.Models.Entity;

namespace StokTakip_Deneme_.Controllers
{
    [Authorize (Roles ="ceo,personel ")]   
    // Bunu yanlızca Rolü "ceo" olan görebilir 
    // Bunu Globalden Toplu olarakdda Yapabiliyoruz ben akılda kalıcı olsun diye ayrı ayrı yaptım 
    public class BirimlerController : Controller
    {

        Stock_Tracking_AppEntities2 db = new Stock_Tracking_AppEntities2();
        public ActionResult Index()
        {
            return View(db.Birimler.ToList());
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(Birimler p )
        {
            if (!ModelState.IsValid)
            {
                return View("Ekle");
            }
            db.Birimler.Add(p);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult GuncelleBilgiGetir(Birimler p)

        {
            var model = db.Birimler.Find(p.ID);

            return View(model);
        }

        public ActionResult Guncelle(Birimler p)
        {
            db.Entry(p).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SilBilgiGetir(Birimler p)
        {

            var model = db.Birimler.Find(p.ID);
            return View(model);
        }


        public ActionResult Sil(Birimler p)
        {

            db.Entry(p).State = System.Data.Entity.EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

StokTakip(Deneme)/Views/Birimler/Ekle.cshtml
@model StokTakip_Deneme_.Models.Entity.Birimler

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Birim Ekleme</h2>

<div class=" container">
    @using (Html.BeginForm("Ekle", "Birimler", FormMethod.Post))
    {
        <div class="form-group">

            @Html.LabelFor(x => x.Birim)

            @Html.TextBoxFor(x => x.Birim, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Birim, "", new { @class = " text-danger" })

        </div>

        <div class="form-group">

            @Html.LabelFor(x => x.Aciklama)

            @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Aciklama, "", new { @class = " text-danger" })

        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Birim Ekle</button>
        </div>



    }

</div>

StokTakip(Deneme)/Views/Birimler/GuncelleBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Birimler

@{
    ViewBag.Title = "GuncelleBilgiGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="container">
    <form action="/Birimler/Guncelle" method="post">
        @Html.AntiForgeryToken()

        <div class="form-group">
            <label for="ID"><b>ID</b></label>
            @Html.TextBoxFor(x => x.ID, new { @class = "form-control"})
        </div>

        <div class="form-group">
            <label for="Birim"><b>Birim</b></label>
            @Html.TextBoxFor(x => x.Birim, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <label for="Aciklama"><b>Açıklama</b></label>
            @Html.TextBoxFor(x => x.Aciklama, new { @class = "form-control" })
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">Birim Güncelle</button>
        </div>
    </form>
</div>

StokTakip(Deneme)/Views/Birimler/Index.cshtml
@using StokTakip_Deneme_.Models.Entity
@model List<StokTakip_Deneme_.Models.Entity.Birimler>

@{
    ViewBag.Title = "Birim Listesi";
}

<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f0f0f0; 
        }

        .div {
            background-color: #e0e0e0; 
            padding: 10px;
            margin-bottom: 10px; 
        }
    </style>
</head>
<body>

    <div class="container">
        <h2>@ViewBag.Title</h2>

        @foreach (var item in Model)
        {
            <div class="div">
                <p><b>ID:</b> @item.ID</p>
                <p><b>Birim:</b> @item.Birim</p>
                <p><b>Açıklama:</b> @item.Aciklama</p>
                <a href="/Birimler/SilBilgiGetir/@item.ID" class="btn btn-danger">Sil</a>
                <a href="/Birimler/GuncelleBilgiGetir/@item.ID" class="btn btn-warning">Güncelle</a>
            </div>
        }

        <div style="width: 250px; margin-top: 10px;">
            <a href="/Birimler/Ekle" class="btn btn-success">Birim Ekle</a>
        </div>
    </div>

</body>
</html>

StokTakip(Deneme)/Views/Birimler/SilBilgiGetir.cshtml
@model StokTakip_Deneme_.Models.Entity.Birimler
    



@{
    ViewBag.Title = "SilBilgiGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SilBilgiGetir</h2>

<div class=" container">




    @using (Html.BeginForm("Sil", "Birimler"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.ID)
        <div class=" form-group">


            @Html.LabelFor(x => x.Birim)
            @Html.DisplayFor(x => x.Birim, new { @class = "form control" })
        </div>
        <div>
            @Html.LabelFor(x => x.Aciklama)
            @Html.DisplayFor(x => x.Aciklama, new { @class = "form control" })
        </div>
        <div>

            <button class=" btn btn-danger">Birim Sil </button>
            <a href="/Birimler/Index">Ana Sayfa</a>
        </div>

    }







</div>